### ISSUE TITLE
flipped the coordinates for the single panel (rotate 180)

### ISSUE THREAD

**Issue by LAutour** [LAutour/ESP32-HUB75-MatrixPanel-I2S-DMA-icn2053#4]
Looks like I've flipped the origin for the single panel. Will be fixed in the next version. For the virtual panel, the coordinates are normal.

**Comment by stsm1964** [comment]
Hi, I am testing the icn2053 library with a single 128x64 p2.5 LED modules with icn2053 drivers.  The image is as you mentioned is rotated 180degree.  May I know when can this issue be fixed?

**Comment by LAutour** [comment]
It will be fixed in the new version (output rotation by 0,90,180,270 and mirroring will be available). I'll post a new version over the weekend.

**Comment by stsm1964** [comment]
Hi LAutour, Thank for your swift response.  
At the means time I am also getting an icn2053 LED module with 1/4 scanning, 32x32 pixel resolution, P6.  Can your icn2053 library drive this module?

**Comment by LAutour** [comment]
This will also be added.

**Comment by LAutour** [comment]
I do not have time to debug - not yet ready.

**Comment by stsm1964** [comment]
Thank you for the progress update.

**Comment by LAutour** [comment]
Fix Rotate and hide and hid the virtual matrix in the main matrix. Due to additional alterations and renaming made a separate version:
https://github.com/LAutour/ESP32-HUB75-MatrixPanel-DMA-ICN2053

**Comment by stsm1964** [comment]
Thank you LAutour for your swift update.  Will test in out tomorrow.

**Comment by stsm1964** [comment]
Tested OK with the new ICN2053 library.  Thank you.
