### ISSUE TITLE
Should it work with 128x64? only every 2nd line used

### ISSUE THREAD

**Issue by Westworld** [LAutour/ESP32-HUB75-MatrixPanel-I2S-DMA-icn2053#5]
Library looks great - and faster than any other I tried.
I have a 128x64 based panel and while the example drives it, only half of the lines are in use.
More exact, first empty, next used (and so on for 15 lines). Then 3 empty ones. Used, unused (repeated for 15 lines). Last two empty. So exactly 30 of the 64 lines are used.

I used the wiring from ESP32-HUB75-MatrixPanel-config_v2.h
In that file, I modified width/height to 128/64, similar to the values in the example itself.

In the read me (translated via DeepL) you write about "four 64x32-Panels", so I'm not sure if it supposed to work with 128x64 panels (using icn2053) at all?

**Comment by LAutour** [comment]
Panel interface 128x64 - HUB75?  1/32scan?

The panel description says 64x32 just for the refresh rate example. I have 80x40 panels  - i check the library for them.

**Comment by LAutour** [comment]
Можно еще фото панели? что выводит, и фото разъема сзади

**Comment by Westworld** [comment]
Sure. Thanks a lot for your fast response and interest.
I have the same board as described here in detail:
http://kuku.eu.org/?projects/hub75e/index
The page has pictures, an interpretation how it works and logic analyzer logs.
It refers to code from a Russian (?) group which works - but only handles 7 FPS
https://bitbucket.org/nadyrshin_ryu/icn2053_esp32_demo/src/master/
Using that code all pixels works - just too slow (I need 25-30 FPS). So I know my panels are working, and found your repository looking for libraries supporting icn2053
The HUB75 has A-C connected, D and E not. The panel has two HUB75 connectors, but both are input (and connected to each other). They do not allow daisy-chaining.

**Comment by LAutour** [comment]
I understand what needs to be done, but first we need to check what code the standard HUB-75 controller is transmitting (next week)

**Comment by Westworld** [comment]
I fear I misunderstood the issue totally, just using the enclosed example, which uses fillscreen. I wondered if the missing lines are moved or excluded, so I modified the example to draw just one pixel - and now realized that the single pixel is vertically replicated. So drawing one pixel, getting a full vertical line (with the described missing ones).

video:
https://github.com/Westworld/HD_DMD_test-/blob/main/example.m4v

Used code:  (inserted in example, after black, before rainbow)
dma_display->setColor(0, 255, 0);
  Serial.println("start pattern");
  int curcounter = 0, counter = 0, y = 0;
  while (counter < (PANE_WIDTH)) {
    for (int x = 0; x < PANE_WIDTH; x++ ) {
          if (curcounter++ == counter)
              dma_display->drawPixelRGB888(x, y, 0, 255, 0);
          else 
              dma_display->drawPixelRGB888(x, y, 0, 0, 0);
      }
    dma_display->flipDMABuffer();
    counter++;
    curcounter=0;
  }

  delay(10000);

I fear that while it is the same chip, it is a very different panel, so not useable at all with this library? Would be too bad...

**Comment by LAutour** [comment]
I know what is needed, but I will have access to the necessary debugging equipment tomorrow.

**Comment by LAutour** [comment]
Not ready yet but will be added in the new repository
https://github.com/LAutour/ESP32-HUB75-MatrixPanel-DMA-ICN2053

**Comment by Westworld** [comment]
super, will try when released and report

**Comment by Westworld** [comment]
Hi, I noticed you mad changes in 
https://github.com/LAutour/ESP32-HUB75-MatrixPanel-DMA-ICN2053
and updated - but got still the same (wrong) effects. Some lines displayed, usually every 2nd with the same color. Was that supposed to work?

To remind, I got exactly the same boards as here described in detail:
http://kuku.eu.org/?projects/hub75e/index

Is there anything I can do to help?
thanks

**Comment by LAutour** [comment]
> Hi, I noticed you mad changes in https://github.com/LAutour/ESP32-HUB75-MatrixPanel-DMA-ICN2053 and updated - but got still the same (wrong) effects. Some lines displayed, usually every 2nd with the same color. Was that supposed to work?
> 
> To remind, I got exactly the same boards as here described in detail: http://kuku.eu.org/?projects/hub75e/index
> 
> Is there anything I can do to help? thanks

it so happened that the discussion of last library is conducted in the old library:
[next_wwek](https://github.com/LAutour/ESP32-HUB75-MatrixPanel-I2S-DMA-icn2053/discussions/6)
(almost everything works there, you need to adjust the timings)

I'll fix it library next week (before I can not).

**Comment by LAutour** [comment]
it is necessary to close discussions in the old library. I'm confused discussing the latest library :(
write in the current version:
ESP32-HUB75-MatrixPanel-DMA-ICN2053
